# Auto-generated by partition_roles.py on 2026-04-27T22:07:10Z
# Provider: registry.terraform.io/SumoLogic/sumologic

# 1 sumologic_partition resource(s)

resource "sumologic_partition" "cloudtrail_infreq" {
  name = "cloudtrail_infreq"
  routing_expression = "_sourcecategory=*cloudtrail* tier=infrequent"
  analytics_tier = "infrequent"
  retention_period = 365
  is_included_in_default_search = false
}
