# Auto-generated by partition_roles.py on 2026-04-27T22:07:10Z
# Provider: registry.terraform.io/SumoLogic/sumologic

# 1 sumologic_role_v2 resource(s)

resource "sumologic_role_v2" "sumo_cloudtrail_infreq_infrequent_partition" {
  name           = "Sumo-cloudtrail_infreq-infrequent-Partition"
  description    = "Auto-generated role for partition cloudtrail_infreq"
  selection_type = "Allow"
  log_analytics_filter  = "*"
  audit_data_filter     = "*"
  security_data_filter  = "*"
  selected_views {
    view_name   = "cloudtrail_infreq"
    view_filter = ""
  }
}
