# Simple test search configuration
# Required: Unique name for this query (used in logging and output filenames)
name: "simple_test"

query: "_sourceCategory=* | count"
from: "-1h"
to: "now"
timeZone: "UTC"
byReceiptTime: false