# Test search job configuration with 2024 timestamps
# Required: Unique name for this query (used in logging and output filenames)
name: "test_count_query"

query: "_sourceCategory=* | count"
from: 1726966800000  # 2024-09-22 13:00:00
to: 1726970400000    # 2024-09-22 14:00:00
timeZone: "UTC"
byReceiptTime: false